// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJ0ItYXJUdYa5sL-JLeVHw5s_TJRKhlY',
    appId: '1:800683276400:web:25d9edbb537bf136a55cb5',
    messagingSenderId: '800683276400',
    projectId: 'ventas-3m',
    authDomain: 'ventas-3m.firebaseapp.com',
    storageBucket: 'ventas-3m.firebasestorage.app',
    measurementId: 'G-CCHS9H1759',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_vxo-pz9LrCTRZsCNUt5tu8ybZ8cqrw',
    appId: '1:800683276400:android:86bdd41870d82d1ca55cb5',
    messagingSenderId: '800683276400',
    projectId: 'ventas-3m',
    storageBucket: 'ventas-3m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2R8guX65C7ja3Y2uwhInvlN6BZduik18',
    appId: '1:800683276400:ios:0f9b7cc5ab7f990ca55cb5',
    messagingSenderId: '800683276400',
    projectId: 'ventas-3m',
    storageBucket: 'ventas-3m.firebasestorage.app',
    iosBundleId: 'com.example.ventas3m',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2R8guX65C7ja3Y2uwhInvlN6BZduik18',
    appId: '1:800683276400:ios:0f9b7cc5ab7f990ca55cb5',
    messagingSenderId: '800683276400',
    projectId: 'ventas-3m',
    storageBucket: 'ventas-3m.firebasestorage.app',
    iosBundleId: 'com.example.ventas3m',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdJ0ItYXJUdYa5sL-JLeVHw5s_TJRKhlY',
    appId: '1:800683276400:web:3b2ca153c76ee7a7a55cb5',
    messagingSenderId: '800683276400',
    projectId: 'ventas-3m',
    authDomain: 'ventas-3m.firebaseapp.com',
    storageBucket: 'ventas-3m.firebasestorage.app',
    measurementId: 'G-9KVQJ98672',
  );
}
